FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
ENV npm_config_audit=false \
    npm_config_fund=false
RUN npm ci --no-audit --no-fund

COPY . .
RUN npm run build -- --configuration production

FROM nginxinc/nginx-unprivileged:1.27-alpine

COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
COPY nginx.prod.conf /etc/nginx/templates/default.conf.template

EXPOSE 8080
