apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: siase
  labels:
    app: siase-app
spec:
  selector:
    app: siase-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
