apiVersion: v1
kind: Secret
metadata:
  name: siase-secret
  namespace: siase
type: Opaque
data:
  DB_USER: c2lhc2VfdXNlcg==
  DB_PASSWORD: REPLACE_DB_PASSWORD_B64
  JWT_SECRET: REPLACE_JWT_SECRET_B64
  WEBHOOK_TOKEN: REPLACE_WEBHOOK_TOKEN_B64
  MECANICO_PASSWORD: REPLACE_MECANICO_PASSWORD_B64
