ALTER TABLE ordens_de_servico DROP CONSTRAINT IF EXISTS ck_os_status;
ALTER TABLE ordens_de_servico ADD CONSTRAINT ck_os_status CHECK (status IN (
    'RECEBIDA', 'EM_DIAGNOSTICO', 'AGUARDANDO_APROVACAO', 'APROVADO',
    'EM_EXECUCAO', 'FINALIZADA', 'ENTREGUE', 'CANCELADA'
));
